{% set name = "ipymesh" %}
{% set version = "0.1.5" %}
{% set build = 0 %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1dab9288b0d781d8797feefc0c551ec80882620fe292881e756e6ecb1369beae

build:
  noarch: python
  number: {{ build }}
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.6.0
    - pip
    - nodejs
  run:
    - python >=3.6.0
    - ipywidgets >=7.0.0

test:
  imports:
    - {{ name }}

about:
  home: https://github.com/erdc/ipymesh
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A Custom Mesh Widget Library
  doc_url: https://github.com/erdc/ipymesh
  dev_url: https://github.com/erdc/ipymesh

extra:
  recipe-maintainers:
    - davidbrochart
